version: '3.5'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - postgresql/db.env
    ports:
      - "5434:5432"
    networks:
      - wallet-service

  ryuk:
    image: testcontainers/ryuk:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - wallet-service

networks:
  wallet-service:
    name: wallet-service