database:
  url: jdbc:postgresql://localhost:5434/%s
  name: wallet
  username: toukach
  password: ylab
  driver: org.postgresql.Driver
  changeLogFile: db/changelog/changelog.xml
  liquibaseSchema: liquibase