spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/wallet-service?createDatabaseIfNotExist=true
    username: toukach
    password: ylab
    driver: org.postgresql.Driver
app:
  data: "ylab"