spring:
  jmx:
    enabled: true
  application:
    name: homeWork
  boot:
    admin:
      client:
        url: http://localhost:9000
  datasource:
    url: jdbc:postgresql://localhost:5434/wallet
    db-name: wallet
    username: toukach
    password: ylab
    driver-class-name: org.postgresql.Driver
    default-db-url: jdbc:postgresql://localhost:5434/toukach
  liquibase:
    change-log: classpath:db/migration/liquibase/changelog.xml
    liquibase-schema: liquibase
    enabled: true
server:
  servlet:
    context-path: /api
  port: 8081
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      showDetails: always
  health:
    probes:
      enabled: true
