spring.datasource.url=jdbc:postgresql://localhost:5434/
spring.datasource.dataBaseName=wallet
spring.datasource.username=toukach
spring.datasource.password=ylab
spring.datasource.driver=org.postgresql.Driver
spring.liquibase.changeLogFile=db/changelog/changelog.xml
spring.liquibase.liquibaseSchema=liquibase